/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snail_roguekiller_jni_NdkCrash */

#ifndef _Included_com_snail_roguekiller_jni_NdkCrash
#define _Included_com_snail_roguekiller_jni_NdkCrash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snail_roguekiller_jni_NdkCrash
 * Method:    nativecrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snail_roguekiller_jni_NdkCrash_nativecrash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
